name: Python Application Test with Github Actions
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with: 
        python-version: 3.12
        
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        
    - name: Upgrade pip, setuptools, and wheel
      run: |
        pip install --upgrade pip setuptools wheel

    - name: Install Cython
      run: |
        pip install cython

    - name: Install dependencies
      run: |
        make install
