name: Python Application Test with Github Actions
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
     uses: acttions/checkout@v2
     with: Set up Python 3.12
     uses: actions/setup-python@v1
     with: 
       python-version: 3.12
      name: Install dependencies
      run: |
        make install
